/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  dockerSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',  // Points to 'quick_start/ruby'
    },
  ],
};

export default sidebars;
