name: Check Links & Spelling

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Links
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --root-dir ${{ github.workspace }}/docs
            --exclude 'dev\.mysql\.com'
            --exclude 'vitepress.dev'
            --exclude 'symfony.com'
            --exclude 'join\.slack\.com'
            --exclude '/img/'
            --verbose
            docs/
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Spelling
        uses: crate-ci/typos@v1.43.0
